### ISSUE TITLE
Incorrect display

### ISSUE THREAD

**Issue by LastSpirit** [WrathChaos/react-native-bouncy-checkbox#101] opened 2022-05-19 09:13 UTC
If you set the width of the border, a space appears
![Screenshot_1](https://user-images.githubusercontent.com/61553803/169258167-b61fd8b1-ad14-410d-8ed9-1e5bd8c538ee.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/61553803/169258192-0ae55e51-fab3-4be0-b976-6282724a7fcd.jpg)

**Comment by WrathChaos** [comment] 2022-05-19 09:49
Hello @LastSpirit,
Don't you think this is normal? Since you set the `borderWidth` it will display a border width :) If I misunderstood you, please explain what is wrong with this?

**Comment by LastSpirit** [comment] 2022-05-21 15:02
Hi @WrathChaos ,
The problem is the white lines inside the square. The border is clearly highlighted

**Comment by TheYuriG** [comment] 2022-07-11 10:24
This will only happen if you change borderWidth. If you only change the radius and don't change the borderWidth, it won't. There must have been some bug calculating the size of the internal icon and animation by literally 1 pixel. Seems like a good first PR for an eager open source contributor.

**Comment by WrathChaos** [comment] 2022-07-26 20:46
Hey @LastSpirit 

Can you give me a full reproducible code? I could not reproduce it with the latest version (2.1.13)

I want to fix it asap

**Comment by TheYuriG** [comment] 2022-07-26 20:59
You can reproduce the issue using the code in the image:
```
<BouncyCheckbox
	onPress={(isChecked) =>
		changeTodoStatus(isChecked, oneOfTheTodos?.id)
	}
	unfillColor={todoColor} //? Inner color of the checkbox
	fillColor={COLORS.checkBox} //? Outer color (radius) of the checkbox
	isChecked={oneOfTheTodos?.completionStatus} //? Checks initial state, doesn't update state yet
	size={35} //? Size of the checkbox
	iconStyle={{
		borderWidth: 3, //? Make the TODO checkbox thicker than default
	}}
></BouncyCheckbox>

![image](https://user-images.githubusercontent.com/63727493/181110643-d53cc01a-56c9-4340-ad1a-07d1d27826a9.png)
Bug still happening to me, my package file says I'm using `^2.1.10`.
```

**Comment by WrathChaos** [comment] 2022-07-26 23:07
@TheYuriG is this iOS or Android?

**Comment by TheYuriG** [comment] 2022-07-26 23:28
> @TheYuriG is this iOS or Android?

Android emulator for me

**Comment by WrathChaos** [comment] 2022-07-27 07:56
Yep, I made it for android. It is working well on iOS but not android. 
I will fix it :) (Hope :D)

**Comment by TheYuriG** [comment] 2022-07-27 07:58
> Thank you for information @TheYuriG 

It's only my pleasure to do something in return for this package. Thanks for getting to it.

**Comment by WrathChaos** [comment] 2022-07-27 12:09
Hey again @TheYuriG  and @LastSpirit 
I fixed it :) 

Also, there are cool changes on animation, please check out the new version:

### [Version 3.0.0 is here 🚀](https://github.com/WrathChaos/react-native-bouncy-checkbox/releases/tag/3.0.0)

**Comment by TheYuriG** [comment] 2022-07-27 13:13
> Hey again @TheYuriG and @LastSpirit I fixed it :) Can you please try this version?

Oh god
![image](https://user-images.githubusercontent.com/63727493/181255594-62115348-1c6b-4f73-8a4e-69fa62b68740.png)

**Comment by WrathChaos** [comment] 2022-07-27 15:02
> 

Thank you for feedback, let me check very fast

**Comment by WrathChaos** [comment] 2022-07-27 15:28
@TheYuriG Found the press problem, fixing it now :)

**Comment by TheYuriG** [comment] 2022-07-27 15:34
> @TheYuriG Found the press problem, fixing it now :) 

Amazing, do you want me to open a separate issue so you can track that independently? Didn't mean to hijack this issue with something else.

**Comment by WrathChaos** [comment] 2022-07-27 15:37
I already fixed it @TheYuriG. Can you please try with version 3.0.1?

**Comment by TheYuriG** [comment] 2022-07-27 21:51
> I already fixed it @TheYuriG. Can you please try with version 3.0.1?

Yeah, both working now.
![image](https://user-images.githubusercontent.com/63727493/181378514-36e37845-80f7-42bc-ac3b-d7ef8293e95c.png)
If you are willing to take feedback, I would center it automatically without putting that responsibility on the developer. This is how your users will expect the module to work, please don't give them extra overhead to manage and boilerplate to write.

As far as I'm concerned, this issue is now fixed and can be closed. Thank you for your work.

**Closed** 2022-07-28 07:30 UTC

**Comment by WrathChaos** [comment] 2022-07-28 07:31
@TheYuriG 
All the feedbacks are welcome :) 
I will set the center into the parent container and release a patch. 

Thank you for testing and helping me out! 🥰

**Comment by TheYuriG** [comment] 2022-07-28 07:36
> Thank you for testing and helping me out! 🥰

No problem, man. Just happy to give something back to the community. :)

**Comment by WrathChaos** [comment] 2022-07-28 07:49
### [Version 3.0.2](https://github.com/WrathChaos/react-native-bouncy-checkbox/releases/tag/3.0.2)

Center styling :) 

@TheYuriG FYI
